name: GitHub Actions Demo
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  checkout-build-test:
    runs-on: ubuntu-latest
    steps:
    - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Installing gtest... (no pre-created action on marketplace?!)
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/libgtest*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - name: Checking out code
      uses: actions/checkout@v2
    - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
    - name: Compiling...
      run: g++ -Wall channel_test.cpp -lgtest -lgtest_main -lpthread
    - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
    - name: Running test...
      run: ./a.out
    - run: echo "ğŸ This job's status is ${{ job.status }}."
